version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    target-branch: release/1.1
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    target-branch: release/1.0
