version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: release/1.1
- package-ecosystem: npm
  directory: "/packages/cli/core"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: release/1.1
- package-ecosystem: npm
  directory: "/packages/cli/core"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: release/1.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: release/1.0
