# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Auto dependency update (v1.0)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

env:
  branch: release/1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ env.branch }}
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install and update dependencies
        run: npm run update
      - name: Commit changed files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git commit -m "Auto dependency update"
      - name: Increment version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna version patch --no-push --yes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch }}
      - name: Read Lerna
        id: lerna
        run: |
          content=`cat ./lerna.json | tr -d "\n"`
          echo "::set-output name=lernaJson::$content"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          release_name: Release ${{fromJson(steps.lerna.outputs.lernaJson).version}}
          tag_name: ${{fromJson(steps.lerna.outputs.lernaJson).version}}
