# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Auto dependency update (v1.1)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

env:
  branch: release/1.1
  level: prerelease

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ env.branch }}
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Install tools
        run: npm i lerna npm-check-updates --no-save
      - name: Update dependencies
        run: npm run ncu
      - name: Install dependencies
        run: npm run udpate
      - name: Commit changed files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git commit -m "Auto dependency update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch }}
