# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Auto dependency update (v1.0)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

env:
  branch: release/1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ env.branch }}
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install and update dependencies
        run: npm run update
      - name: Commit changed files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git commit -m "Auto dependency update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch }}
      - name: Increment version
        run: npx lerna version patch --no-push --yes
      - name: Commit changed files 1
        run: |
#          git config --local user.email "github@martinoppitz.com"
#          git config --local user.name "Martin Oppitz"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git commit -m "Auto increment version"
      - name: Push changes 2
        uses: ad-m/github-push-action@master
        with:
#         github_token: ${{ secrets.GIT_PUSH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch }}
