# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create Leanup CLI

on:
  workflow_dispatch:

env:
  access: public
  alias: leanup
  registry: https://registry.npmjs.org
  tag: next
  token: ${{ secrets.NPMJS_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: '${{env.registry}}'
          scope: '@${{env.alias}}'
      - name: Install and publish only @${{env.alias}}/stack-snowpack
        run: |
          npm install
          npm pack
        working-directory: packages/cli/create-leanup
