# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Create a Release

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          scope: '@leanup'
      # // https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson
      - name: Read Lerna
        id: lerna
        run: |
          content=`cat ./lerna.json | tr -d "\n"`
          echo "::set-output name=lernaJson::$content"
      # - name: Install
      #   run: npm ci
      # - name: Coverage
      #   run: npx do coverage
      # // https://github.com/actions/create-release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{fromJson(steps.lerna.outputs.lernaJson).version}}
          release_name: Release ${{fromJson(steps.lerna.outputs.lernaJson).version}}
          draft: true
          prerelease: false
