# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test Node 12, 13, 14 and NPM 6

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        framework: [angular, angularjs, inferno, lit-element, preact, react, svelte, vanilla, vue, vue3]
        leanup: [latest]
        node: [14]
        # node: [12, 13, 14]
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: (${{matrix.framework}}) / ${{matrix.leanup}} / Node ${{ matrix.node }} / ${{ matrix.os }}
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm run update
      - name: Test all framework variants
        run: |
          rm ../.eslintrc.js
          sh wake-up.sh ${{matrix.framework}} leanup next
        working-directory: scripts
