# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: NPM dist tag

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action'
        required: false
        default: 'add'
      version:
        description: 'Version'
        required: true
        default: '1.0.'
      tag:
        description: 'Tag'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run npm dist-tag
        run: |
          npm dist-tag ${{ github.event.inputs.action }} ${{ github.event.inputs.vesion }} ${{ github.event.inputs.tag }}
