# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Publish to NPM

on:
  workflow_dispatch:
  release:
    types:
      - released

env:
  access: public
  alias: leanup
  registry: https://registry.npmjs.org
  tag: next
  token: ${{ secrets.NPMJS_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: '${{env.registry}}'
          scope: '@${{env.alias}}'
      - name: Clear npm cache
        run: npm cache clean -f
      - name: Install and publish only @${{env.alias}}/stack
        run: |
          rm package-lock.json
          npm install --legacy-peer-deps
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/stack/core
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish only @${{env.alias}}/stack-vite
        run: |
          rm package-lock.json
          npm install --legacy-peer-deps
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/stack/bundlers/vite
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish only @${{env.alias}}/stack-webpack
        run: |
          rm package-lock.json
          npm install --legacy-peer-deps
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/stack/bundlers/webpack
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish only @${{env.alias}}/lib
        run: |
          rm package-lock.json
          npm install --legacy-peer-deps
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/lib
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish only @${{env.alias}}/stack-plugin-babel
        run: |
          rm package-lock.json
          npm install --legacy-peer-deps
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/stack/plugins/babel
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish non @${{env.alias}}/lib, @${{env.alias}}/stack, @${{env.alias}}/stack-plugin-babel, @${{env.alias}}/stack-vite and @${{env.alias}}/stack-webpack
        run: |
          rm -rf packages/stack/core/dist packages/stack/webpack/dist
          npx lerna exec --ignore @template/* --ignore @${{env.alias}}/lib --ignore @${{env.alias}}/stack --ignore @${{env.alias}}/stack-plugin-babel --ignore @${{env.alias}}/stack-vite --ignore @${{env.alias}}/stack-webpack --stream -- npm install --legacy-peer-deps
          npx lerna exec --ignore @template/* --ignore @${{env.alias}}/lib --ignore @${{env.alias}}/stack --ignore @${{env.alias}}/stack-plugin-babel --ignore @${{env.alias}}/stack-vite --ignore @${{env.alias}}/stack-webpack --no-bail --stream -- npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Test all framework variants
        run: |
          rm ../.eslintrc.js
          sh wake-up-all.sh ${{env.alias}} ${{env.tag}}
        working-directory: scripts
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
