# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Publish to NPM

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  tag: next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@leanup'
      - name: Install and publish only @leanup/lib
        run: |
          npm install
          npm publish --access=public --tag=${{env.tag}} || true
        working-directory: packages/lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli-core-babel
        run: |
          npm install
          npm publish --access=public --tag=${{env.tag}} || true
        working-directory: packages/cli/core/babel
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli-core-e2e
        run: |
          ls -la
          npm install
          npm publish --access=public --tag=${{env.tag}} || true
        working-directory: packages/cli/core/e2e
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli-core-format
        run: |
          npm install
          npm publish --access=public --tag=${{env.tag}} || true
        working-directory: packages/cli/core/format
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli-core-lint
        run: |
          npm install
          npm publish --access=public --tag=${{env.tag}} || true
        working-directory: packages/cli/core/lint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli-core-test
        run: |
          npm install
          npm publish --access=public --tag=${{env.tag}} || true
        working-directory: packages/cli/core/test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/stack-webpack
        run: |
          npm install
          npm publish --access=public --tag=${{env.tag}} || true
        working-directory: packages/stack/webpack
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/stack
        run: |
          sleep 60
          npm install
          npm publish --access=public --tag=${{env.tag}} || true
        working-directory: packages/stack/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli
        run: |
          npm install
          npm publish --access=public --tag=${{env.tag}} || true
        working-directory: packages/cli/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish non @leanup/cli, @leanup/cli-core-e2e, @leanup/cli-core-format, @leanup/cli-core-lint, @leanup/cli-core-test and @leanup/lib
        run: |
          sleep 60
          npx lerna exec --ignore @template/* --ignore @leanup/cli --ignore @leanup/stack --ignore @leanup/stack-webpack --ignore @leanup/cli-core-e2e --ignore @leanup/cli-core-format --ignore @leanup/cli-core-lint --ignore @leanup/cli-core-test --ignore @leanup/lib --stream -- npm install
          npx lerna exec --ignore @template/* --ignore @leanup/cli --ignore @leanup/stack --ignore @leanup/stack-webpack --ignore @leanup/cli-core-e2e --ignore @leanup/cli-core-format --ignore @leanup/cli-core-lint --ignore @leanup/cli-core-test --ignore @leanup/lib --no-bail --stream -- npm publish --access=public --tag=${{env.tag}} || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Test all framework variants
        run: |
          rm ../.eslintrc.js
          sh wake-up-all.sh ${{github.event.inputs.tag}}
        working-directory: scripts
