# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Publish to NPM

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@leanup"
      - name: Install and publish only @leanup/cli-core-e2e
        run: |
          npm install
          npm publish --access public || true
        working-directory: cli/core/e2e
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli-core-format
        run: |
          npm install
          npm publish --access public || true
        working-directory: cli/core/format
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli-core-lint
        run: |
          npm install
          npm publish --access public || true
        working-directory: cli/core/lint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli-core-test
        run: |
          npm install
          npm publish --access public || true
        working-directory: cli/core/test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish only @leanup/cli
        run: |
          npm install
          npm publish --access public || true
        working-directory: cli/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - name: Install and publish non @leanup/cli, @leanup/cli-core-e2e, @leanup/cli-core-format, @leanup/cli-core-lint and @leanup/cli-core-test
        run: |
          npx lerna exec --ignore @template/* --ignore @leanup/cli --ignore @leanup/cli-core-e2e --ignore @leanup/cli-core-format --ignore @leanup/cli-core-lint --ignore @leanup/cli-core-test --stream -- npm install
          npx lerna exec --ignore @template/* --ignore @leanup/cli --ignore @leanup/cli-core-e2e --ignore @leanup/cli-core-format --ignore @leanup/cli-core-lint --ignore @leanup/cli-core-test --no-bail --stream -- npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
