# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Publish to NPM (DRY)

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  tag: next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://unix.stackexchange.com/questions/112023/how-can-i-replace-a-string-in-a-files
      - name: Replace alias in all package.json's
        run: |
          find .  -name "package.json" -type f
          find .  -name "package.json" -type f -exec sed -i 's/"@leanup\//"@leanupjs\//g' {} +
          git diff
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@leanupjs'
      - name: Install and publish only @leanupjs/stack-webpack
        run: |
          npm install
          npm publish --access=restricted --tag=${{env.tag}} || true
        working-directory: packages/stack/webpack
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install and publish only @leanupjs/stack
        run: |
          npm install
          npm publish --access=restricted --tag=${{env.tag}} || true
        working-directory: packages/stack/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install and publish only @leanupjs/lib
        run: |
          npm install
          npm publish --access=restricted --tag=${{env.tag}} || true
        working-directory: packages/lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install and publish only @leanupjs/cli-core-babel
        run: |
          npm install
          npm publish --access=restricted --tag=${{env.tag}} || true
        working-directory: packages/cli/core/babel
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install and publish only @leanupjs/cli
        run: |
          npm install
          npm publish --access=restricted --access=public --tag=${{env.tag}} || true
        working-directory: packages/cli/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install and publish non @leanupjs/cli, @leanupjs/cli-core-babel, @leanupjs/lib, @leanupjs/stack and @leanupjs/stack-webpack
        run: |
          npx lerna exec --ignore @template/* --ignore @leanupjs/cli --ignore @leanupjs/cli-core-babel --ignore @leanupjs/lib --ignore @leanupjs/stack --ignore @leanupjs/stack-webpack --stream -- npm install
          npx lerna exec --ignore @template/* --ignore @leanupjs/cli --ignore @leanupjs/cli-core-babel --ignore @leanupjs/lib --ignore @leanupjs/stack --ignore @leanupjs/stack-webpack --no-bail --stream -- npm publish --access=restricted --tag=${{env.tag}} || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test all framework variants
        run: |
          rm ../.eslintrc.js
          sh wake-up-all.sh ${{env.tag}}
        working-directory: scripts
